name: pharmexpo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  carousel_pro: ^1.0.0
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  date_format: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/drawer.webp
    - images/cadu.jpg
    - images/ph.jpg
    - images/bv.jpg
    - images/labo/avene.png
    - images/labo/bioderma.jfif
    - images/labo/acm.png
    - images/labo/bo.jfif
    - images/labo/eye.png
    - images/labo/filor.png
#    - images/labo/lrp.jpg
    - images/labo/nore.jfif
    - images/labo/nux.jfif
    - images/labo/pf.png
    - images/labo/svr.png
    - images/labo/uri.jfif
    - images/labo/vichy.jpg
    - images/labo/avene/avcima.jfif
    - images/labo/avene/avclex.jfif
    - images/labo/avene/avclge.jfif
    - images/labo/avene/aveath150.jfif
    - images/labo/avene/avecmi.jfif
    - images/labo/avene/avhyle.jfif
    - images/labo/avene/avhyop.jfif
    - images/labo/avene/avhyri.jfif
    - images/labo/avene/avsosu.jfif
    - images/labo/avene/avtrex.jfif
    - images/indication/chutche.jfif
    - images/indication/compl.jfif
    - images/indication/ecrn.jfif
    - images/indication/hessence.jfif
    - images/indication/labo.png
    - images/indication/main.jfif
    - images/indication/pied.jfif
    - images/indication/rides.jfif
    - images/indication/shamp.jfif
    - images/indication/tache.jfif
    - images/indication/teinture.jfif
    - images/indication/visage.jfif
    - images/ageperson/adult.jfif
    - images/ageperson/enfant.png
    - images/ageperson/bebe.jfif
    - images/rsocial/g.png
    - images/rsocial/f.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
